name: Check EntryPoint and EIP-155 Support

on:
  issue_comment:
    types: [created]

jobs:
   check-support:
    runs-on: ubuntu-latest
    if: >-
      github.event.issue.pull_request == null && github.event.comment.user.login != 'github-actions[bot]' &&
      (contains(github.event.comment.body, 'check ')) && github.event.action == 'created'
    steps:
      - name: Extract RPC URL
        id: extract
        run: |
          RPC_URL=$(echo "${{ github.event.comment.body }}" | grep -oP '(https?:\/\/[^\s]+)')
          echo "::set-output name=rpc-url::$RPC_URL"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Script
        id: run-script
        run: echo "::set-output name=result::$(./checkEP.sh ${{ steps.extract.outputs.rpc-url }})"
      - name: Comment with Result
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            @${{ github.event.comment.user.login }} asked for a check:
            > ${{ github.event.comment.body }}
            
            Result for RPC URL: ${{ steps.extract.outputs.rpc-url }}:
            ${{ steps.run-script.outputs.result }}
          token: ${{ secrets.PAT_SECRET }}
